In [85]:
#вывод текста на экран
print('Привет мир')

Привет мир


# Целые, вещественные и комплексные числа; Строки

In [86]:
#операция присваивания
#assignment operation
x=5
#Вывод информации в консоль
#Print the value of x
print(x)

5


In [87]:
# тип integer - целое число
type(x)

int

In [88]:
# тип str - строка (текст)/string
x='Hello'
type(x)

str

In [89]:
# тип complex - комплексное число/complex number
x=5+7j
print(x)
type(x)

(5+7j)


complex

In [90]:
#тип float - число с плавающей запятой, рациональное число
x = 11.3
type(x)

float

In [91]:
#операция деления / division
print (x/2)

5.65


In [92]:
#операция умножения / multiplication
print (x*2)

22.6


In [93]:
#возведение в степень / exponentiation
print (x**3)

1442.8970000000002


In [94]:
#разделить и показать целую часть от деления
#Floor division operation (divide and show the integer part of the division)
print (x//2)

5.0


In [95]:
#разделить и показать остаток
#Modulo operation (divide and show the remainder)
print (x%2)

1.3000000000000007


In [96]:
print(x)

11.3


In [97]:
x=x**10
print(x)

33945673899.22225


In [98]:
a=5
b=3.5

In [99]:
# a=a+b
a+=b
print(a)

8.5


In [100]:
# a=a-b
a-=b
print(a)

5.0


In [101]:
# a=a*b
a*=b
print(a)

17.5


In [102]:
# a=a/b
a/=b
print(a)

5.0


In [103]:
# проверка a>b
# check whether a is higher than a
a>b

True

In [104]:
# проверка a<b
# check whether a is lower than a
a<b

False

In [105]:
# проверка a больше или равно b
# check whether a is higher or equal than a
a>=b

True

In [106]:
# проверка a!=b
# check whether a does not equal to a
a!=b

True

# Списки, кортежи, множества и словари (List, tuple, set, dictionary)

Тип список. Список - упорядоченный, индексируемый,
изменяемый набор данных разного типа

In [107]:
x=[4, 6, 4, 6.4, 'Hello', 9+7j]
'''
Тип список. Список - упорядоченный, индексируемый,
изменяемый набор данных разного типа

List type. A list is an ordered,
indexed, mutable collection of
heterogeneous data.
'''
type(x)

list

In [108]:
'''
обращение к элементу списка
номер элемента в списке начинается с нуля

Accessing an element in the list.
List indexing starts from 0.
'''
x[0]

4

In [109]:
'''
нижняя граница всегда включается,
верхняя граница всегда исключается => и <

Slicing the list. The lower bound is always
included, and the upper bound is always excluded.
'''
x[1:3]

[6, 4]

In [110]:
'''
вывод до конца списка
Slicing from a specific index to the end of the list.
'''
x[1:]

[6, 4, 6.4, 'Hello', (9+7j)]

In [111]:
'''
вывод с конца списка
Accessing elements from the end of the list.
Negative indices count from the end of the list.
'''
x[:-2]

[4, 6, 4, 6.4]

In [112]:
'''
[start:stop:step] - начало - конец - шаг.
начинаем со второго числа в списке,
заканчиваем на шестом элементе,
шаг 2 - через одно число в списке

Slicing with a step. [start:stop:step] - start, stop, step.
Starting from the second element, ending at
the sixth element (exclusive), step by 2.
'''
x[1:6:2]

[6, 6.4, (9+7j)]

In [113]:
'''
переворот списка
Reversing the list
'''
x[::-1]

[(9+7j), 'Hello', 6.4, 4, 6, 4]

In [114]:
'''
пример изменения списка
Example of changing a list
'''
x=[1, 2, 3]
x[1]=70
print(x)

[1, 70, 3]


In [115]:
'''
кортеж (tuple) - упорядоченный, индексируемый,
неизменяемый набор данных разного типа.
Отличие от типа - в списке можно
изменять элементы, а в кортеже нет

Tuple creation. A tuple is an ordered,
indexed, immutable collection of heterogeneous data.
'''
x=(1,4,7,8)
type(x)

tuple

In [116]:
'''
Множество - неупорядоченный, неиндексируемый,
но изменяемый набор данных разного типа.

A set is a collection which is unordered,
unchangeable*, and unindexed.
*Note: Set items are unchangeable,
but you can remove items and add new items.
'''
x={1,4,"Hello",6, 6, 8}
print(x)
type(x)

{1, 4, 6, 8, 'Hello'}


set

In [117]:
'''
выводит только уникальные значения
highlight only unique values
'''
list(set(x))

[1, 4, 6, 8, 'Hello']

In [118]:
'''
можно превратить множество или кортеж в список и потом с ним работать
Converting a set or tuple into a list to perform operations
'''
x=list(x)
type(x)

list

In [119]:
'''
Словари - неупорядоченные коллекции
произвольных объектов с доступом по ключу.

Dictionaries are used to store data values in key:value pairs.

A dictionary is a collection which is ordered*,
changeable and do not allow duplicates.

*As of Python version 3.7, dictionaries are ordered.
In Python 3.6 and earlier, dictionaries are unordered.
'''
x={'Greetings':['Hello', 'Hi','Good morning'],
  'hasta la vista': ['Bye', 'Good bye']}
print(x)

{'Greetings': ['Hello', 'Hi', 'Good morning'], 'hasta la vista': ['Bye', 'Good bye']}


In [120]:
# обращение к элементу словаря
# Accessing an element of the dictionary
print(x['hasta la vista'] [0])

Bye


In [121]:
# обращение к ключу словаря. выдает привет
# Accessing dictionary keys. Outputs 'Greetings'
print(list(x.keys()) [0] )

Greetings


In [122]:
# обращение к ключу словаря. выдает пока
# Accessing dictionary keys. Outputs 'hasta la vista'
print(list(x.keys()) [1] )

hasta la vista


# Библиотека numpy и массивы

In [123]:
'''
#импортируем библиотеку numpy и вводим
краткое обозначение названия библиотеки.
Обозначение может быть любым,
но библиотеку Numpy принято обозначать как np


Importing the numpy library and abbreviating its name as np
'''
import numpy as np

'''
Представление данных в виде одномерного массива (array).
С этим массивом можно производить математические
операции как в линейной алгебре.

Loading data into a one-dimensional array using numpy array.
With these arrays, you can perform mathematical operations as
in linear algebra.
'''
x=np.array([1,2,3,4])
type(x)

numpy.ndarray

In [124]:
y=[4,5,6,7]
type(y)

list

In [125]:
'''
Printing the list y multiplied by 3
Вывод результата операции: умножить список на 3
'''
print(y*3)
'''
Printing the array x multiplied by 2
Вывод результата операции умножения одномерного
массива (каждого его элемента) на 3
'''
print(x*2)
'''
Printing the result of dividing each element in array x by 2
Вывод результата операции деления одномерного
массива (каждого его элемента) на 2
'''
print(x/2)
'''
Printing the result of raising each element in array x to the power of 4
Вывод результата операции возведения одномерного
массива (каждого его элемента) в четвертую степень
'''
print(x**4)

[4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[  1  16  81 256]


In [126]:
#обращение к элементам как в списках
#accessing items the same as in lists
x[1]

2

In [127]:
#двумерный массив, как матрица. табличные данные для анализа
#a two-dimensional array, like a matrix. tabular data for analysis
x=np.array([[1,2],[3,4]])
print(x)
#обращение к элементу двумерного массива
#accessing an element of a two-dimensional array.
x[1,0]

[[1 2]
 [3 4]]


3

In [128]:
#округление. по умолчанию до целого числа
#rounding up. by default, up to an integer
print(np.round (5/3))
#округлям до n числа знаков после запятой
#rounding up to n the number of decimal places
print(np.round (5/3, 6))
#округление в большую сторону
#rounding up
print(np.ceil(1/4))
#округление в меньшую сторону сторону
#rounding down
print(np.floor(1/4))

2.0
1.666667
1.0
0.0


#УСЛОВИЯ

In [129]:
# Генерация случайного числа в диапазоне [0, 100)
# Generate a random number between 0 and 1 and store it in the variable z

z = (np.random.random())*100
# Проверка условия, что число больше 70
# Checking the condition that the number is greater than 70
if z > 70:
    # Вывод сообщения "Excellent"
    print("Excellent")
    # Вывод значения числа, округленного
    # до двух знаков после запятой
    print(round(z, 2))
elif z<=70 and z>50:
    print("Satisfactory")
    print(round(z, 2))
# Во всех остальных случаях,
# когда число меньше или равно 50
else:
  print("Not satisfactory")
  print(round(z, 2))

Excellent
99.51


#FOR, WHILE, CONTINUE

In [130]:
# Создание списка друзей
# Create a list of friends
friends = ['Joseph', 'Glenn', 'Sally']
# Цикл для каждого друга в списке друзей
# Loop for each friend in the friends list
for friend in friends:
    # Вывод имени друга
    # Output of a friend's name
    print(friend)

Joseph
Glenn
Sally


In [131]:
# Цикл для каждого друга в списке друзей
# Loop for each friend in the friends list
for friend in friends:
    # Вывод сообщения "Happy New Year:" и имени друга
    # The output of the message "Happy New Year:" and the name of a friend
    print('Happy New Year:', friend)
    # Вывод сообщения "Done!" после каждого друга
    # The output of the "Done!" message After every friend
    print('Done!')

Happy New Year: Joseph
Done!
Happy New Year: Glenn
Done!
Happy New Year: Sally
Done!


In [132]:
# Задание начального значения переменной num
# Setting the initial value of the num variable
num = 10
# Цикл, выполняющийся до тех пор, пока num меньше 30
# A loop that runs until num is less than 30
while num < 30:
    # Вывод текущего значения num
    # Output of the current num value
    print(num)
    # Увеличение значения num на 5
    # Increasing the num value by 5
    num = num + 5

10
15
20
25
